/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ProgramRouteImport } from './routes/program'
import { Route as LpjRouteImport } from './routes/lpj'
import { Route as KontakRouteImport } from './routes/kontak'
import { Route as KegiatanRouteImport } from './routes/kegiatan'
import { Route as GaleriRouteImport } from './routes/galeri'
import { Route as BeritaRouteImport } from './routes/berita'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminKegiatanRouteImport } from './routes/admin.kegiatan'
import { Route as AdminGaleriRouteImport } from './routes/admin.galeri'
import { Route as AdminDokumenRouteImport } from './routes/admin.dokumen'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBeritaRouteImport } from './routes/admin.berita'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAnggotaRouteImport } from './routes/admin.anggota'

const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramRoute = ProgramRouteImport.update({
  id: '/program',
  path: '/program',
  getParentRoute: () => rootRouteImport,
} as any)
const LpjRoute = LpjRouteImport.update({
  id: '/lpj',
  path: '/lpj',
  getParentRoute: () => rootRouteImport,
} as any)
const KontakRoute = KontakRouteImport.update({
  id: '/kontak',
  path: '/kontak',
  getParentRoute: () => rootRouteImport,
} as any)
const KegiatanRoute = KegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriRoute = GaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => rootRouteImport,
} as any)
const BeritaRoute = BeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKegiatanRoute = AdminKegiatanRouteImport.update({
  id: '/kegiatan',
  path: '/kegiatan',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGaleriRoute = AdminGaleriRouteImport.update({
  id: '/galeri',
  path: '/galeri',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDokumenRoute = AdminDokumenRouteImport.update({
  id: '/dokumen',
  path: '/dokumen',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBeritaRoute = AdminBeritaRouteImport.update({
  id: '/berita',
  path: '/berita',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnggotaRoute = AdminAnggotaRouteImport.update({
  id: '/anggota',
  path: '/anggota',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/kegiatan': typeof KegiatanRoute
  '/kontak': typeof KontakRoute
  '/lpj': typeof LpjRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/admin/anggota': typeof AdminAnggotaRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/kegiatan': typeof AdminKegiatanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/kegiatan': typeof KegiatanRoute
  '/kontak': typeof KontakRoute
  '/lpj': typeof LpjRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/admin/anggota': typeof AdminAnggotaRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/kegiatan': typeof AdminKegiatanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/berita': typeof BeritaRoute
  '/galeri': typeof GaleriRoute
  '/kegiatan': typeof KegiatanRoute
  '/kontak': typeof KontakRoute
  '/lpj': typeof LpjRoute
  '/program': typeof ProgramRoute
  '/tentang': typeof TentangRoute
  '/admin/anggota': typeof AdminAnggotaRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/berita': typeof AdminBeritaRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/dokumen': typeof AdminDokumenRoute
  '/admin/galeri': typeof AdminGaleriRoute
  '/admin/kegiatan': typeof AdminKegiatanRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/berita'
    | '/galeri'
    | '/kegiatan'
    | '/kontak'
    | '/lpj'
    | '/program'
    | '/tentang'
    | '/admin/anggota'
    | '/admin/audit-log'
    | '/admin/berita'
    | '/admin/dashboard'
    | '/admin/dokumen'
    | '/admin/galeri'
    | '/admin/kegiatan'
    | '/admin/settings'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/berita'
    | '/galeri'
    | '/kegiatan'
    | '/kontak'
    | '/lpj'
    | '/program'
    | '/tentang'
    | '/admin/anggota'
    | '/admin/audit-log'
    | '/admin/berita'
    | '/admin/dashboard'
    | '/admin/dokumen'
    | '/admin/galeri'
    | '/admin/kegiatan'
    | '/admin/settings'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/berita'
    | '/galeri'
    | '/kegiatan'
    | '/kontak'
    | '/lpj'
    | '/program'
    | '/tentang'
    | '/admin/anggota'
    | '/admin/audit-log'
    | '/admin/berita'
    | '/admin/dashboard'
    | '/admin/dokumen'
    | '/admin/galeri'
    | '/admin/kegiatan'
    | '/admin/settings'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BeritaRoute: typeof BeritaRoute
  GaleriRoute: typeof GaleriRoute
  KegiatanRoute: typeof KegiatanRoute
  KontakRoute: typeof KontakRoute
  LpjRoute: typeof LpjRoute
  ProgramRoute: typeof ProgramRoute
  TentangRoute: typeof TentangRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program': {
      id: '/program'
      path: '/program'
      fullPath: '/program'
      preLoaderRoute: typeof ProgramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lpj': {
      id: '/lpj'
      path: '/lpj'
      fullPath: '/lpj'
      preLoaderRoute: typeof LpjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontak': {
      id: '/kontak'
      path: '/kontak'
      fullPath: '/kontak'
      preLoaderRoute: typeof KontakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kegiatan': {
      id: '/kegiatan'
      path: '/kegiatan'
      fullPath: '/kegiatan'
      preLoaderRoute: typeof KegiatanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeri': {
      id: '/galeri'
      path: '/galeri'
      fullPath: '/galeri'
      preLoaderRoute: typeof GaleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berita': {
      id: '/berita'
      path: '/berita'
      fullPath: '/berita'
      preLoaderRoute: typeof BeritaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/kegiatan': {
      id: '/admin/kegiatan'
      path: '/kegiatan'
      fullPath: '/admin/kegiatan'
      preLoaderRoute: typeof AdminKegiatanRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/galeri': {
      id: '/admin/galeri'
      path: '/galeri'
      fullPath: '/admin/galeri'
      preLoaderRoute: typeof AdminGaleriRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dokumen': {
      id: '/admin/dokumen'
      path: '/dokumen'
      fullPath: '/admin/dokumen'
      preLoaderRoute: typeof AdminDokumenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/berita': {
      id: '/admin/berita'
      path: '/berita'
      fullPath: '/admin/berita'
      preLoaderRoute: typeof AdminBeritaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/anggota': {
      id: '/admin/anggota'
      path: '/anggota'
      fullPath: '/admin/anggota'
      preLoaderRoute: typeof AdminAnggotaRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnggotaRoute: typeof AdminAnggotaRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminBeritaRoute: typeof AdminBeritaRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDokumenRoute: typeof AdminDokumenRoute
  AdminGaleriRoute: typeof AdminGaleriRoute
  AdminKegiatanRoute: typeof AdminKegiatanRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnggotaRoute: AdminAnggotaRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminBeritaRoute: AdminBeritaRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDokumenRoute: AdminDokumenRoute,
  AdminGaleriRoute: AdminGaleriRoute,
  AdminKegiatanRoute: AdminKegiatanRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BeritaRoute: BeritaRoute,
  GaleriRoute: GaleriRoute,
  KegiatanRoute: KegiatanRoute,
  KontakRoute: KontakRoute,
  LpjRoute: LpjRoute,
  ProgramRoute: ProgramRoute,
  TentangRoute: TentangRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
